### ISSUE TITLE
AttributeError when patching with py3 version script

### ISSUE THREAD

**Issue by shellkr** [ryanoasis/nerd-fonts#79]
I am trying to patch PragmataPro with `--fontawesome`, `--powerlineextra` and `--octicon` but it fails. If I only try `--powerline` and `--pomicons` it works. 

**Coomand I run:** `fontforge -script font-patcher-py3 $HOME/PragmataPro/PragmataPro.ttf --fontawesome --powerline --powerlineextra --pomicons --octicons`

**Which gives the traceback:**

    ...
    Traceback (most recent call last):
    File "font-patcher-py3", line 467, in <module>
    copy_glyphs(sourceFont, sourceFontFontAwesomeStart, sourceFontFontAwesomeEnd, 
    fontawesome, symbolsFontAwesomeRangeStart, symbolsFontAwesomeRangeEnd, True)
    File "font-patcher-py3", line 343, in copy_glyphs
    copiedToSlot = str(sym_glyph.str)
    AttributeError: 'fontforge.glyph' object has no attribute 'str'

Similar error if I remove `--fontawesome` for the other flags.

#### My Setup

- _PragmataPro, Knack Regular Nerd Font Complete Mono.ttf_
- _Arch Linux, Urxvt, Zsh, libfontforge 20150928 and libfontforge 20160427_

**Comment by ryanoasis** [comment]
Hey, sorry I just haven't had time to look into this but I promise you I will. Thanks :+1:

**Comment by kazuoteramoto** [comment]
Looks like the problem was introduced in 019bf46269e0b7598eb380d151c263e67488acec `.unicode` is the unicode code point of `glyph` not a unicode encoded string.

If you apply this sees to work
```diff
diff --git i/font-patcher-py3 w/font-patcher-py3
index c2392c2..849ad80 100755
--- i/font-patcher-py3
+++ w/font-patcher-py3
@@ -340,7 +340,7 @@ def copy_glyphs(sourceFont, sourceFontStart, sourceFontEnd, symbolFont, symbolFo
             if exactEncoding:
                 # use the exact same hex values for the source font as for the symbol font
                 currentSourceFontGlyph = sym_glyph.encoding
-                copiedToSlot = str(sym_glyph.str)
+                copiedToSlot = str(sym_glyph.unicode)
             else:
                 # use source font defined hex values based on passed in start and end
                 # convince that this string really is a hex:
```

**Comment by shellkr** [comment]
Can confirm that the patch works. No more errors.

**Comment by shellkr** [comment]
However the patching doesn't seem to have worked. The powerline is not in sync and FontAwesome is not shown. As shown in the screenshot below.

![screenshot](https://ptpb.pw/4Qqi.png)

**Comment by ryanoasis** [comment]
@shellkr @kazuoteramoto Thanks for testing it out and the info here.

Seems that I was warned about 2to3 changing unicode to str (see #49) so my bad there.

I can confirm the same error, but the change @kazuoteramoto pointed out seems to work for me:

`fontforge -script font-patcher-py3 ../temp/nerd-fonts/PragmataPro.ttf --powerline --powerlineextra --fontawesome`

![selection_29_04_16_21 05 59_122x41_001](https://cloud.githubusercontent.com/assets/8083459/14932964/3d65d192-0e4e-11e6-8b6d-5f32a54b167a.png)

granted i just copy and pasted the literal characters directly into the terminal :sweat_smile:

**Comment by shellkr** [comment]
@ryanoasis What terminal is that? And you can see the powerline is a bit off in yours too. If you have a terminal which supports fontconfig it will look in all your fonts for glyphs. So you only need one font among all that is okay and it will work. It might not be the patched font you see in that image.

**Comment by ryanoasis** [comment]
You are correct I need to make sure to clear out my patched fonts, I will try a less lazy test today.

Yeah the powerline symbols are definitely off

**Comment by shellkr** [comment]
Ok, seems like the issue is mainly with Urxvt. https://github.com/FortAwesome/Font-Awesome/issues/3681. I got it working with the help of 'xft:SauceCodePro NF:pixelsize=9' as a fallback in my ~/.Xresources though. So it should be possible to get PragmataPro to work too somehow.. not sure how.

![FontAwesome working](https://ptpb.pw/E3Vl.png)

**Comment by ryanoasis** [comment]
Going to make a bash script to do the 2to3 conversion because of this.

https://docs.python.org/2/library/2to3.html#to3-fixers

>
unicode
    Renames unicode to str.

**Comment by ryanoasis** [comment]
@shellkr If you are still having trouble patching PragmataPro or some other font issues feel free to open a separate issue. I am going to close this one (the AttributeError) for [0.8.0 release](https://github.com/ryanoasis/nerd-fonts/milestones/v0.8.0) which I am almost done with :smile:
